import logging

logger = logging.getLogger(__name__)

class EventPublisher:
    """
    Central event publisher interface.
    As per Event Contracts, publishes immutable events generated by domain services.
    """
    @staticmethod
    def publish(event_name: str, event_version: int, correlation_id: str, occurred_at, producer: str, data: dict):
        logger.info(f"Published Event: {event_name} (Correlation: {correlation_id}) from {producer}")

event_publisher = EventPublisher()
