# Generated by Django 5.1.15 on 2026-06-15 12:43

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unscheduled", "Unscheduled"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="unscheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled start time in UTC.",
                        null=True,
                        verbose_name="Start Time",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled end time in UTC.",
                        null=True,
                        verbose_name="End Time",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the technician transitioned to in_progress.",
                        null=True,
                        verbose_name="Actual Start Time",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated duration in integer days.",
                        null=True,
                        verbose_name="Duration (Days)",
                    ),
                ),
                (
                    "reschedule_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Reschedule Count"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        help_text="The parent Request this booking fulfills.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="requests.request",
                        verbose_name="Request",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        help_text="Denormalized from Request.assigned_technician for DB constraints.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoShowRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        help_text="Links this record to the original transaction context.",
                        verbose_name="Correlation ID",
                    ),
                ),
                (
                    "absent_party",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("technician", "Technician"),
                        ],
                        max_length=20,
                        verbose_name="Absent Party",
                    ),
                ),
                (
                    "declared_at",
                    models.DateTimeField(
                        help_text="Timestamp of declaration used to verify 2-hour grace period.",
                        verbose_name="Declared At",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The user who reported the no-show.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="no_show_record",
                        to="bookings.booking",
                        verbose_name="Booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "No-Show Record",
                "verbose_name_plural": "No-Show Records",
            },
        ),
        migrations.CreateModel(
            name="RescheduleRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(
                        help_text="Links this record to the original transaction context.",
                        verbose_name="Correlation ID",
                    ),
                ),
                ("previous_start_time", models.DateTimeField(blank=True, null=True)),
                ("previous_end_time", models.DateTimeField(blank=True, null=True)),
                ("new_start_time", models.DateTimeField()),
                ("new_end_time", models.DateTimeField()),
                (
                    "reason_code",
                    models.CharField(max_length=50, verbose_name="Reason Code"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="The user who initiated the reschedule.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedule_history",
                        to="bookings.booking",
                        verbose_name="Booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reschedule Record",
                "verbose_name_plural": "Reschedule Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schedule_blob",
                    models.JSONField(
                        help_text="JSON blob defining active days and UTC start/end times.",
                        verbose_name="Schedule Data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "technician",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Working Hours",
                "verbose_name_plural": "Working Hours",
            },
        ),
        migrations.CreateModel(
            name="BlackoutDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="UTC start of blackout.", verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="UTC end of blackout.", verbose_name="End Time"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blackout_dates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Technician",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blackout Date",
                "verbose_name_plural": "Blackout Dates",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="blackout_end_after_start",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("reschedule_count__lte", 3)),
                name="max_reschedule_limit_3",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__gt", models.F("start_time")),
                    ("start_time__isnull", True),
                    ("end_time__isnull", True),
                    _connector="OR",
                ),
                name="booking_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status__in", ["scheduled", "in_progress"])),
                expressions=[
                    ("technician", "="),
                    (
                        django.db.models.expressions.RawSQL(
                            "tstzrange(start_time, end_time)", []
                        ),
                        "&&",
                    ),
                ],
                name="prevent_technician_double_booking",
            ),
        ),
    ]
