# Generated by Django 5.1.15 on 2026-06-15 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "start_time", "end_time"],
                name="bookings_bo_status_d2d474_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["technician", "status"], name="bookings_bo_technic_f9149b_idx"
            ),
        ),
    ]
