# Generated by Django 5.1.15 on 2026-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_bookings_bo_status_d2d474_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="last_reminder_sent",
            field=models.DateTimeField(
                blank=True,
                help_text="Tracks idempotency for reminder dispatch.",
                null=True,
                verbose_name="Last Reminder Sent",
            ),
        ),
    ]
