[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = -ra --strict-markers
markers =
    asyncio: mark test as asyncio-based.
    anyio: mark test as anyio-based.

