# Generated by Django architecture setup (manual migration).

import uuid

import django.core.validators
from django.db import migrations, models

import apps.users.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        verbose_name="active",
                        help_text=(
                            "Designates whether this user should be treated as active. "
                            "Unselect this instead of deleting accounts."
                        ),
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        verbose_name="staff status",
                        help_text="Designates whether the user can log into this admin site.",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        verbose_name="superuser status",
                        help_text=(
                            "Designates that this user has all permissions without "
                            "explicitly assigning them."
                        ),
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        primary_key=True,
                        serialize=False,
                        editable=False,
                        default=uuid.uuid4,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        verbose_name="email address",
                        max_length=254,
                        unique=True,
                        db_index=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=32,
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.RegexValidator(
                                regex=r"^$|^\+?[0-9\-\s\(\)]{7,20}$",
                                message="Enter a valid phone number or leave blank.",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=32,
                        choices=[
                            ("SUPER_ADMIN", "Super Admin"),
                            ("MANAGER", "Manager"),
                            ("STAFF", "Staff"),
                            ("TECHNICIAN", "Technician"),
                            ("CUSTOMER", "Customer"),
                        ],
                        default="CUSTOMER",
                        db_index=True,
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, db_index=True),
                ),
                (
                    "phone_verified",
                    models.BooleanField(default=False, db_index=True),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "last_password_change_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, db_index=True),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("mfa_enabled", models.BooleanField(default=False)),
                (
                    "profile_image",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. A user will get all "
                            "permissions granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users_user",
                "ordering": ("email",),
            },
            managers=[
                ("objects", apps.users.managers.UserManager()),
            ],
        ),
    ]
