# Generated by Django 5.1.15 on 2026-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_active_alter_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
