# Generated by Django 5.1.15 on 2026-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_locked_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_version",
            field=models.PositiveIntegerField(
                default=1, help_text="Increment when permissions/roles change"
            ),
        ),
    ]
