# Generated by Django 5.1.15 on 2026-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_technicianapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianapplication",
            name="form_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
