# Generated by Django 5.1.15 on 2026-05-20 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0005_seed_audit_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogentry",
            name="occurred_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, help_text="When event actually happened"
            ),
            preserve_default=False,
        ),
    ]
