# Generated by Django 5.1.15 on 2026-05-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit_logs",
            "0006_rename_audit_logs_retention_idx_audit_logs__retenti_3aa39e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_logs__retenti_3aa39e_idx",
            old_name="audit_logs_retention_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="audit_logs__legal_h_e9c50b_idx",
            old_name="audit_logs_hold_archive_idx",
        ),
    ]
