# Generated by Django 5.1.15 on 2026-07-20 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audit_logs",
            "0007_rename_audit_logs_retention_idx_audit_logs__retenti_3aa39e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="audit_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
