# Generated by Django 5.1.15 on 2026-07-28 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0008_alter_auditlogentry_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogentry",
            name="actor_name",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="actor_role",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="module",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="new_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="old_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="request_method",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="request_path",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="severity",
            field=models.CharField(db_index=True, default="info", max_length=32),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="source",
            field=models.CharField(blank=True, default="API", max_length=64),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="status",
            field=models.CharField(db_index=True, default="success", max_length=32),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="target_display",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="target_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="target_type",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
