# Generated by Django 5.1.15 on 2026-06-22 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=255)),
                ("actor_id", models.CharField(max_length=255)),
                ("actor_type", models.CharField(max_length=50)),
                ("correlation_id", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "audit_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
