# Generated by Django 5.1.15 on 2026-06-10 12:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("installation", "Installation"),
                            ("inspection", "Inspection"),
                            ("maintenance", "Maintenance"),
                            ("support", "Support"),
                            ("information", "Information"),
                            ("booking", "Booking"),
                            ("product_order", "Product Order"),
                            ("device_outage", "Device Outage"),
                            ("consultation", "Consultation"),
                            ("warranty", "Warranty"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency"),
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("staff_review", "Staff Review"),
                            ("awaiting_quote", "Awaiting Quote"),
                            (
                                "awaiting_customer_approval",
                                "Awaiting Customer Approval",
                            ),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("awaiting_assignment", "Awaiting Assignment"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("pending_verification", "Pending Verification"),
                            ("completed", "Completed"),
                            ("escalated", "Escalated"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.JSONField(blank=True, null=True)),
                ("decline_count", models.IntegerField(default=0)),
                ("sla_target_time", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Compliant"),
                            ("warning", "Warning"),
                            ("breached", "Breached"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_requests",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=50,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("THREE_DECLINES_THRESHOLD", "Three Declines Threshold"),
                            ("SLA_BREACH", "SLA Breach"),
                            ("EMERGENCY_DEVICE_OUTAGE", "Emergency Device Outage"),
                            ("MANUAL_MANAGER_REVIEW", "Manual Manager Review"),
                            (
                                "REPEATED_VERIFICATION_FAILURE",
                                "Repeated Verification Failure",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved")],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the escalation. Null if system triggered.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triggered_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalations",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation",
                "verbose_name_plural": "Escalations",
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decline_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TECHNICIAN_UNAVAILABLE", "Technician Unavailable"),
                            ("TECHNICIAN_OUT_OF_REGION", "Technician Out Of Region"),
                            ("TECHNICIAN_SKILL_MISMATCH", "Technician Skill Mismatch"),
                            (
                                "TECHNICIAN_WORKLOAD_CAPACITY",
                                "Technician Workload Capacity",
                            ),
                            (
                                "TECHNICIAN_PERSONAL_EMERGENCY",
                                "Technician Personal Emergency",
                            ),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
            },
        ),
        migrations.CreateModel(
            name="StateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("staff_review", "Staff Review"),
                            ("awaiting_quote", "Awaiting Quote"),
                            (
                                "awaiting_customer_approval",
                                "Awaiting Customer Approval",
                            ),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("awaiting_assignment", "Awaiting Assignment"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("pending_verification", "Pending Verification"),
                            ("completed", "Completed"),
                            ("escalated", "Escalated"),
                            ("cancelled", "Cancelled"),
                        ],
                        help_text="Previous state. Null if this is the initial creation.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("staff_review", "Staff Review"),
                            ("awaiting_quote", "Awaiting Quote"),
                            (
                                "awaiting_customer_approval",
                                "Awaiting Customer Approval",
                            ),
                            ("awaiting_payment", "Awaiting Payment"),
                            ("awaiting_assignment", "Awaiting Assignment"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("pending_verification", "Pending Verification"),
                            ("completed", "Completed"),
                            ("escalated", "Escalated"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("correlation_id", models.UUIDField(db_index=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the transition. Null if performed by the system.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="state_history",
                        to="requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "State History",
                "verbose_name_plural": "State Histories",
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("overridden", "Overridden"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("override_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="requests.request",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification",
                "verbose_name_plural": "Verifications",
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("signed_checklist", "Signed Checklist"),
                            ("customer_acknowledgement", "Customer Acknowledgement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_url", models.URLField(max_length=1024)),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geo_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("device_timestamp", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="requests.verification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence",
                "verbose_name_plural": "Evidence",
            },
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["status", "category"], name="requests_re_status_78042e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["customer", "status"], name="requests_re_custome_5cc0fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["assigned_technician", "status"],
                name="requests_re_assigne_7f0a15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["sla_status", "sla_target_time"],
                name="requests_re_sla_sta_9a1126_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["status", "expires_at"], name="requests_qu_status_e411c7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(
                fields=("request", "version"), name="unique_quote_version"
            ),
        ),
        migrations.AddIndex(
            model_name="escalation",
            index=models.Index(
                fields=["status", "created_at"], name="requests_es_status_191a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statehistory",
            index=models.Index(
                fields=["request", "timestamp"], name="requests_st_request_06b34b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="verification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("request",),
                name="unique_pending_verification",
            ),
        ),
    ]
