# Generated by Django 5.1.15 on 2026-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="requires_technician",
            field=models.BooleanField(default=False),
        ),
    ]
