# Generated by Django 5.1.15 on 2026-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0002_request_requires_technician"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="verification_evidence/"
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="file_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
