# Generated by Django 5.1.15 on 2026-07-04 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "Unread"),
                            ("READ", "Read"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="UNREAD",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("PUSH", "Push"),
                            ("WEBSOCKET", "WebSocket"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DEAD_LETTERED", "Dead Lettered"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("provider_response", models.JSONField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notification.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("PUSH", "Push")], max_length=50
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "status", "created_at"],
                name="notificatio_recipie_ed8115_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="notificatio_resourc_2b1836_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["status"], name="notificatio_status_82c106_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user"], name="notificatio_user_id_597e9a_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "category", "channel"),
                name="unique_user_category_channel_preference",
            ),
        ),
    ]
