# Generated by Django 5.1.15 on 2026-07-18 13:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=255, unique=True)),
                ("subject", models.CharField(max_length=255)),
                ("html_body", models.TextField()),
                ("plain_text_body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="provider_error_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="provider_error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="provider_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="provider_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="request_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="response_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notificationdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("SENT", "Sent"),
                    ("DELIVERED", "Delivered"),
                    ("FAILED", "Failed"),
                    ("DEAD_LETTERED", "Dead Lettered"),
                    ("BOUNCED", "Bounced"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="DeliveryRetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                ("reason", models.TextField()),
                (
                    "backoff_delay",
                    models.IntegerField(
                        help_text="Delay in seconds before this retry was attempted"
                    ),
                ),
                ("outcome", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retries",
                        to="notification.notificationdelivery",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
