# Generated by Django 5.1.15 on 2026-07-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notificationtemplate_notification_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdelivery",
            name="correlation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
