# Generated by Django 5.1.15 on 2026-06-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default="PENDING", max_length=100, unique=True),
        ),
    ]
