from enum import Enum

class RequestAction(str, Enum):
    SUBMIT = "submit"
    PICK_UP = "pick_up"
    NEEDS_QUOTE = "needs_quote"
    REQUIRE_PAYMENT = "require_payment"
    ASSIGN_DIRECTLY = "assign_directly"
    ISSUE_QUOTE = "issue_quote"
    APPROVE_QUOTE_PAYMENT_REQ = "approve_quote_payment_req"
    APPROVE_QUOTE_NO_PAYMENT = "approve_quote_no_payment"
    REQUEST_REVISION = "request_revision"
    REJECT_QUOTE = "reject_quote"
    PAYMENT_WEBHOOK = "payment_webhook"
    ASSIGN_TECH = "assign_tech"
    ACCEPT = "accept"
    DECLINE = "decline"
    TIMEOUT = "timeout"
    MARK_FINISHED = "mark_finished"
    MARK_FINISHED_NO_VERIFICATION = "mark_finished_no_verification"
    APPROVE_VERIFICATION = "approve_verification"
    REJECT_VERIFICATION = "reject_verification"
    OVERRIDE_VERIFICATION = "override_verification"
    CANCEL = "cancel"
    CANCEL_ACTIVE = "cancel_active"
    ESCALATE = "escalate"
    RESOLVE_ESCALATION = "resolve_escalation"
